export type CardListItem = {
  img: string,
  value: string,
  isOpened: boolean,
  id: number,
  completed: boolean,
}


const cardsList: CardListItem[] = [
  {
    img: '/images/Agent.jpg',
    value: 'agent',
    isOpened: false,
    id: 1,
    completed: false,
  },
  {
    img: '/images/Agent.jpg',
    value: 'agent',
    isOpened: false,
    id: 2,
    completed: false,
  },
  {
    img: '/images/Archer.jpg',
    value: 'archer',
    isOpened: false,
    id: 3,
    completed: false,
  },
  {
    img: '/images/Archer.jpg',
    value: 'archer',
    isOpened: false,
    id: 4,
    completed: false,
  },
  {
    img: '/images/Assasin.jpg',
    value: 'assasin',
    isOpened: false,
    id: 5,
    completed: false,
  },
  {
    img: '/images/Assasin.jpg',
    value: 'assasin',
    isOpened: false,
    id: 6,
    completed: false,
  },
  {
    img: '/images/Barbarian.jpg',
    value: 'barbarian',
    isOpened: false,
    id: 7,
    completed: false,
  },
  {
    img: '/images/Barbarian.jpg',
    value: 'barbarian',
    isOpened: false,
    id: 8,
    completed: false,
  },
  {
    img: '/images/Bard.jpg',
    value: 'bard',
    isOpened: false,
    id: 9,
    completed: false,
  },
  {
    img: '/images/Bard.jpg',
    value: 'bard',
    isOpened: false,
    id: 10,
    completed: false,
  },
  {
    img: '/images/Helper.jpg',
    value: 'helper',
    isOpened: false,
    id: 11,
    completed: false,
  },
  {
    img: '/images/Helper.jpg',
    value: 'helper',
    isOpened: false,
    id: 12,
    completed: false,
  },
  {
    img: '/images/Knight.jpg',
    value: 'knight',
    isOpened: false,
    id: 13,
    completed: false,
  },
  {
    img: '/images/Knight.jpg',
    value: 'knight',
    isOpened: false,
    id: 14,
    completed: false,
  },
  {
    img: '/images/Magic.jpg',
    value: 'magic',
    isOpened: false,
    id: 15,
    completed: false,
  },
  {
    img: '/images/Magic.jpg',
    value: 'magic',
    isOpened: false,
    id: 16,
    completed: false,
  },
  {
    img: '/images/Theif.jpg',
    value: 'theif',
    isOpened: false,
    id: 17,
    completed: false,
  },
  {
    img: '/images/Theif.jpg',
    value: 'theif',
    isOpened: false,
    id: 18,
    completed: false,
  },
]

export default cardsList